---
dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=tin-summer

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu  # FEATURES="simd pattern"
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl  # FEATURES="simd"
      rust: nightly

    # OSX
    - env: TARGET=x86_64-apple-darwin  # FEATURES="simd pattern"
      os: osx
      rust: nightly

    # *BSD
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1  # FEATURES="simd"
      rust: nightly
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1  # FEATURES="simd"
      rust: nightly

    # Other architectures
    - env: TARGET=aarch64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=armv7-unknown-linux-musleabihf
      rust: nightly
    - env: TARGET=sparc64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=arm-unknown-linux-gnueabi
      rust: nightly
    - env: TARGET=arm-unknown-linux-musleabi
      rust: nightly
    - env: TARGET=sparcv9-sun-solaris DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=x86_64-sun-solaris DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-steed DISABLE_TESTS=1  # FEATURES="simd"
      rust: nightly
    - env: TARGET=armv7-unknown-linux-steedeabihf DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=arm-unknown-linux-steedeabi DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=aarch64-unknown-linux-steed DISABLE_TESTS=1
      rust: nightly
    - env: TARGET=x86_64-pc-windows-gnu
      rust: nightly

  # Allowed failures
  allow_failures:
    - env: TARGET=x86_64-unknown-linux-steed DISABLE_TESTS=1
    - env: TARGET=armv7-unknown-linux-steedeabihf DISABLE_TESTS=1
    - env: TARGET=arm-unknown-linux-steedeabi DISABLE_TESTS=1
    - env: TARGET=aarch64-unknown-linux-steed DISABLE_TESTS=1
    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=arm-unknown-linux-musleabi
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=sparc64-unknown-linux-gnu
    - env: TARGET=armv7-unknown-linux-musleabihf
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=arm-unknown-linux-musleabi
    - env: TARGET=sparcv9-sun-solaris DISABLE_TESTS=1
    - env: TARGET=x86_64-sun-solaris DISABLE_TESTS=1
    - env: TARGET=sparcv9-sun-solaris DISABLE_TESTS=1  # FEATURES="simd"
    - env: TARGET=x86_64-sun-solaris DISABLE_TESTS=1  # FEATURES="simd"

before_install: set -e

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh
  - |
    if [ `echo $TARGET` = "x86_64-unknown-linux-gnu" ]
    then
      curl -sL https://raw.githubusercontent.com/vmchale/tomlcheck/master/sh/check | sh -s Cargo.toml
    else
      echo 'skipping tomlcheck download...'
    fi

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
  # - Paste the output down here
  api_key:
    secure: "ivQk+/3qAGHwqhhqp35ltxrOQMRpyDyfBQ2tOxNcnCPfstLRFJo8wkv8rNfMrn0h2e0u9pr1/7PXwANURjh0tPtRR33b65WesruyZWtLtVtN+uYHQWLuMxsgN+xpO/sO6/TWiEDU0pQS5U+8Ch+V2XpganSzFYyU3Z6lO5R4sC4m2cfBEJLBwFTUp89fx6fcidNkcz7KoIKOLMsyFI/wIEkQXTv8FXorKArLXQP4KrsO9psv3sKuD+AEFfkzS396ihKbAvd0vjb9OZs98V7Fih0e2M2DYzzAR2ymKSFRjpU2agi/d5KZG2mJdn+IWfVIXpo8Y7Nc4amC4M+783fyWdxGt0Ed6vzIwPIVQmSqqE6ITluKTRS3ICe2+lgWSWHzRIg6l/aG+nGZOALeKbOUr1WC58LLFbdTToykHVFVbWRWhuDCNruGRxl4dUPw2oDTicTlpLDh4qel/YcPfCvzLoRdZ3zckuwbNseQp5eBABbk9aFioJi83bd6Na2+dZVukSWGO+u9Z4Z6HOM54keFaPdaqGSjMCX81WgQE2LGxLBtflxGNRh4jzQ2M5cpPcFunH2AYIqpkiGkYTQeWJFMik1WPfkD8CXxirCEcpN8b570fND411VInTNLRCBMW/uOQDGbAMiWwtSfCLPIVdo0nA/4wg6eVNaX5P/ntvu/ht0="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /\d+\.\d+\.\d+.*$/
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
