[package]
name = "file-sniffer"
version = "0.1.1"
authors = ["Vanessa McHale <vamchale@gmail.com>"]
license-file = "LICENSE"
description = "Command-line tool to find build artifacts and junk on your computer."
readme = "README.md"
repository = "https://github.com/vmchale/file-sniffer"
documentation = "https://github.com/vmchale/file-sniffer#README"
homepage = "https://github.com/vmchale/file-sniffer" # consider hosting on http://vmchale.com/ ?
test = false

[dependencies]
colored = "1.5"
clap = {version = "2.24", features = ["yaml"]}
pad = "0.1"
regex = "0.2"

[lib]
path = "src/lib.rs"
name = "libsniff"

[[bin]]
path = "src/main.rs"
name = "sniff"
